# 🚫 CI deaktivert – vi bruker kun Vercel for build og deploy

name: CI (disabled)

# CI kjøres aldri – bare aktiv på en ikke-eksisterende gren
on:
  push:
    branches: [ __never__ ]
  pull_request:
    branches: [ __never__ ]

jobs:
  skip:
    runs-on: ubuntu-latest
    steps:
      - run: echo "CI er deaktivert – bygg håndteres av Vercel ✅"
